version: '3.8'

services:

  db-server:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: testdb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db-server
    depends_on:
      - db-server

  frontend:
    image: node:20-slim
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    depends_on:
      - backend